const SPACETRADERS_BASE_URL = import.meta.env.VITE_SPACETRADERS_BASE_URL
const SPACETRADERS_REGISTER_URL = `${SPACETRADERS_BASE_URL}${import.meta.env.VITE_SPACETRADERS_REGISTER_URL}`
const SPACETRADERS_SYSTEMS_URL = `${SPACETRADERS_BASE_URL}${import.meta.env.VITE_SPACETRADERS_SYSTEMS_URL}`
const SPACETRADERS_WAYPOINTS_URL = `${import.meta.env.VITE_SPACETRADERS_WAYPOINTS_URL}`
const SPACETRADERS_MY_AGENT_URL = `${SPACETRADERS_BASE_URL}${import.meta.env.VITE_SPACETRADERS_MY_AGENT_URL}`
const SPACTRADERS_MY_CONTRACTS_URL = `${SPACETRADERS_BASE_URL}${import.meta.env.VITE_SPACETRADERS_MY_CONTRACTS_URL}`
const SPACE_TRADERS_ACCEPT_CONTRACT_URL = `${import.meta.env.VITE_SPACETRADERS_ACCEPT_CONTRACT_URL}`

export {
  SPACETRADERS_REGISTER_URL,
  SPACETRADERS_SYSTEMS_URL,
  SPACETRADERS_WAYPOINTS_URL,
  SPACETRADERS_MY_AGENT_URL,
  SPACTRADERS_MY_CONTRACTS_URL,
  SPACE_TRADERS_ACCEPT_CONTRACT_URL,
}
